# Nordic Colorscheme for Ghostty.
# Based on https://github.com/AlexvZyl/nordic.nvim
# Author: @jorgebef

# To use this theme you have 2 options to install it:
#
# - Clone the theme file and set the theme option in your config to the absolute path of the theme file.
# Example:
#
# ```ini
# theme = "/home/jbef/.config/ghostty/nordic"
# ```
#
# - Copy the code directly inside your `ghostty` configuration file, usually located at `$HOME/.config/ghostty/config`

background = #232533
foreground = #BCC0D5
cursor-color = #BCC0D5
selection-background = #2E3140
selection-foreground = #BCC0D5

palette = 0=#191B29
palette = 1=#BF616A
palette = 2=#A3BE8C
palette = 3=#EBCB8B
palette = 4=#5E81AC
palette = 5=#88C0D0
palette = 6=#B48EAD
palette = 7=#D7D7E8

palette = 8=#3B3952
palette = 9=#C5727A
palette = 10=#B1C89D
palette = 11=#EFD49F
palette = 12=#88C0D0
palette = 13=#BE9DB8
palette = 14=#9FC6C5
palette = 15=#EFEFF8
