# abbr rm "rm -i"
# abbr cp "cp -i"
# abbr mv "mv -i"
# abbr mkdir "mkdir -p"
# abbr h "history"
# abbr which "type -a"
# abbr ls "exa -lag --header"
abbr dev "cd ~/Developer"
abbr dots "cd ~/Developer/dotfiles/"
abbr dropbox "cd ~/Library/CloudStorage/Dropbox/"

abbr ssh-peninsula "ssh root@188.34.186.187"
