[*]
ctx-size = 0
jinja = on
; kv-unified = 1
; parallel = 4
; spec-default = 1

[Qwen3.8-27B-UD-Q6_K_XL]
model = /Users/jbef/models/unsloth/Qwen3.8-27B-GGUF/Qwen3.8-27B-UD-Q6_K_XL.gguf
mmproj = /Users/jbef/models/unsloth/Qwen3.8-27B-GGUF/mmproj-F16.gguf
ctx-size = 131072
mmproj-offload = false
flash-attn = on
ngl = 99
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4
spec-ngram-mod-n-match = 24
reasoning = on
; reasoning-level = medium
chat-template-kwargs = {"reasoning_effort":"medium"}
host = 127.0.0.1
port = 8080
