local cp = require("catppuccin.core.palettes.macchiato")

vim.api.nvim_set_hl(0, "Pmenu", { bg = cp.surface0 })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = cp.mauve, bg = cp.surface1 })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = cp.mauve, bg = cp.surface0 })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = cp.mauve })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { fg = cp.mauve })

vim.api.nvim_set_hl(0, "BufferLineIndicatorSelected", { fg = cp.mauve })
vim.api.nvim_set_hl(0, "BufferlineModified", { fg = cp.red })
vim.api.nvim_set_hl(0, "BufferLineModifiedVisible", { fg = cp.red })
vim.api.nvim_set_hl(0, "BufferLineModifiedSelected", { fg = cp.red })
vim.api.nvim_set_hl(0, "BufferLineBufferVisible", { fg = cp.text })

vim.api.nvim_set_hl(0, "BufferLineDuplicateSelected", { fg = cp.text, bg = cp.base })
vim.api.nvim_set_hl(0, "BufferLineDuplicateVisible", { fg = cp.text, bg = cp.base })
vim.api.nvim_set_hl(0, "BufferLineDuplicate", { fg = cp.overlay2, bg = cp.base })

vim.api.nvim_set_hl(0, "TelescopePreviewTitle", { fg = cp.mauve })
vim.api.nvim_set_hl(0, "TelescopeResultsTitle", { fg = cp.mauve })
vim.api.nvim_set_hl(0, "TelescopePromptTitle", { fg = cp.mauve })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { fg = cp.sapphire })
vim.api.nvim_set_hl(0, "TelescopeMatching", { fg = cp.mauve })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = cp.red, bg = cp.surface0 })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = cp.overlay0 })

vim.api.nvim_set_hl(0, "WinBar", { bg = cp.surface0 })
vim.api.nvim_set_hl(0, "WinBarNC", { bg = cp.base })
vim.api.nvim_set_hl(0, "WinBarIndicatorSelected", { fg = cp.mauve, bg = cp.surface0 })
vim.api.nvim_set_hl(0, "WinbarActiveFileName", { fg = cp.text, bg = cp.surface0, bold = true })
vim.api.nvim_set_hl(0, "WinbarActiveGPS", { fg = cp.subtext1, bg = cp.surface0 })
vim.api.nvim_set_hl(0, "WinbarInactiveFileName", { fg = cp.overlay2, bg = cp.base, bold = true })
vim.api.nvim_set_hl(0, "WinbarInactiveGPS", { fg = cp.surface1, bg = cp.base })
vim.api.nvim_set_hl(0, "WinBarInactiveModified", { fg = cp.red, bg = cp.surface0 })
vim.api.nvim_set_hl(0, "WinBarActiveModified", { fg = cp.red, bg = cp.base })
