#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Use karabiner elements to remap right Command key to function key

# Automatically float non-resizable windows, such as palettes, system settings etc.
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | /opt/homebrew/bin/jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# Make all windows float by default
yabai -m rule --add app=".*" manage=off
yabai -m rule --add app=".*" sub-layer=normal

# Manage these windows only
yabai -m rule --add app="^Arc$" manage=on
# yabai -m rule --add app="^Adobe.*" manage=on
# yabai -m rule --add app="^Google Chrome$" manage=on
# yabai -m rule --add app="^WezTerm$" manage=on
yabai -m rule --add app="^Ghostty$" manage=on
yabai -m rule --add app="^WezTerm$" manage=on
yabai -m rule --add app="^Google Chrome$" manage=on
yabai -m rule --add app="^Firefox Nightly$" manage=on
yabai -m rule --add app="^Zen Browser$" manage=on

# global settings
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_topmost off \
  window_shadow off \
  window_animation_duration 0.0 \
  window_opacity_duration 0.0 \
  window_zoom_persist off \
  window_opacity off \
  active_window_opacity 1.0 \
  normal_window_opacity 1.0 \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 10 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 10 \
  layout bsp \
  mouse_modifier ctrl \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap
