#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
#  79470451c0240b6bfa43665fbdeb40c066cf36a305ce78c4f7816953a77901e0  /opt/homebrew/bin/yabai


yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# # Automatically float non-resizable windows, such as palettes, system settings etc.
yabai -m signal --add event=window_created action='
  yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || \
  yabai -m window $YABAI_WINDOW_ID --toggle float && \
  yabai -m window $YABAI_WINDOW_ID --layer above && \
  yabai -m window $YABAI_WINDOW_ID --grid 3:3:1:1:1:1
'

# yabai -m rule --add label="Firfox PIP" app="^Firefox$" title="^(Picture-in-Picture)$" manage=off

yabai -m signal --add event=window_destroyed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# # focus window after active display changes
# yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

yabai -m rule --add app=".*" sub-layer=normal
# Make all windows float by default
yabai -m rule --add app=".*" manage=off

# Manage these windows only
yabai -m rule --add app="^Arc$" manage=on
yabai -m rule --add app="^Ghostty$" manage=on
yabai -m rule --add app="^WezTerm$" manage=on
yabai -m rule --add app="^Google Chrome$" manage=on
yabai -m rule --add app="^Vivaldi$" manage=on
yabai -m rule --add app="^Firefox Nightly$" manage=on
yabai -m rule --add app="^Zen$" manage=on
# yabai -m rule --add app="^Adobe.*" manage=on
# yabai -m rule --add app="^Google Chrome$" manage=on

# global settings
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_topmost off \
  window_shadow off \
  window_animation_duration 0.0 \
  window_opacity_duration 0.0 \
  window_zoom_persist off \
  window_opacity off \
  active_window_opacity 1.0 \
  normal_window_opacity 1.0 \
  insert_feedback_color 0xffd75f5f \
  split_ratio 1 \
  auto_balance off \
  top_padding 10 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 10

# yabai -m config layout stack
yabai -m config layout bsp
yabai -m config mouse_drop_action swap

# yabai -m config mouse_modifier ctrl
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize
