local catppuccin = require("catppuccin")

-- IMPORTANT!!!!!!!!!
vim.g.catppuccin_flavour = "mocha"
local cp = require("catppuccin.palettes").get_palette()

catppuccin.setup({
  dim_inactive = {
    enabled = false,
    shade = "dark",
    percentage = 0.15,
  },
  transparent_background = false,
  term_colors = false,
  compile = {
    enabled = true,
    path = vim.fn.stdpath("cache") .. "/catppuccin",
    suffix = "_compiled",
  },
  styles = {
    comments = { "italic" },
    conditionals = { "italic" },
    loops = {},
    functions = {},
    keywords = {},
    strings = {},
    variables = {},
    numbers = {},
    booleans = {},
    properties = {},
    types = {},
    operators = {},
  },
  integrations = {
    treesitter = true,
    native_lsp = {
      enabled = true,
      virtual_text = {
        errors = { "italic" },
        hints = { "italic" },
        warnings = { "italic" },
        information = { "italic" },
      },
      underlines = {
        errors = { "underline" },
        hints = { "underline" },
        warnings = { "underline" },
        information = { "underline" },
      },
    },
    coc_nvim = false,
    lsp_trouble = false,
    cmp = true,
    lsp_saga = true,
    gitgutter = false,
    gitsigns = true,
    telescope = true,
    nvimtree = {
      enabled = true,
      show_root = true,
      transparent_panel = false,
    },
    neotree = {
      enabled = false,
      show_root = true,
      transparent_panel = false,
    },
    which_key = true,
    indent_blankline = {
      enabled = true,
      colored_indent_levels = false,
    },
    dashboard = true,
    neogit = false,
    vim_sneak = false,
    fern = false,
    barbar = false,
    bufferline = false,
    markdown = true,
    lightspeed = false,
    ts_rainbow = false,
    hop = false,
    notify = true,
    telekasten = false,
    symbols_outline = true,
    mini = false,
    leap = true,
  },
  -- color_overrides = {},
  -- highlight_overrides = {},
  custom_highlights = {
    -- UI elements
    -- ===============================================================================
    -- Pmenu = { bg = cp.surface0 },
    Pmenu = { bg = cp.base },
    PmenuSel = { fg = cp.text, bg = cp.surface1, bold = true },
    -- NormalFloat = { bg = cp.surface0 },
    NormalFloat = { bg = cp.base },
    -- FloatBorder = { fg = cp.blue, bg = cp.surface0 },
    FloatBorder = { fg = cp.blue, bg = cp.base },

    CmpItemAbbrMatch = { fg = cp.pink },
    CmpItemAbbrMatchFuzzy = { fg = cp.pink },
    CmpItemMenu = { fg = cp.overlay0, bg = nil, italic = true },
    -- CmpItemKindField = { fg = "#EED8DA", bg = "#B5585F" },
    -- CmpItemKindProperty = { fg = "#EED8DA", bg = "#B5585F" },
    -- CmpItemKindEvent = { fg = "#EED8DA", bg = "#B5585F" },
    -- CmpItemKindText = { fg = "#C3E88D", bg = "#9FBD73" },
    -- CmpItemKindEnum = { fg = "#C3E88D", bg = "#9FBD73" },
    -- CmpItemKindKeyword = { fg = "#C3E88D", bg = "#9FBD73" },
    -- CmpItemKindConstant = { fg = "#FFE082", bg = "#D4BB6C" },
    -- CmpItemKindConstructor = { fg = "#FFE082", bg = "#D4BB6C" },
    -- CmpItemKindReference = { fg = "#FFE082", bg = "#D4BB6C" },
    -- CmpItemKindFunction = { fg = "#EADFF0", bg = "#A377BF" },
    -- CmpItemKindStruct = { fg = "#EADFF0", bg = "#A377BF" },
    -- CmpItemKindClass = { fg = "#EADFF0", bg = "#A377BF" },
    -- CmpItemKindModule = { fg = "#EADFF0", bg = "#A377BF" },
    -- CmpItemKindOperator = { fg = "#EADFF0", bg = "#A377BF" },
    -- CmpItemKindVariable = { fg = "#C5CDD9", bg = "#7E8294" },
    -- CmpItemKindFile = { fg = "#C5CDD9", bg = "#7E8294" },
    -- CmpItemKindUnit = { fg = "#F5EBD9", bg = "#D4A959" },
    -- CmpItemKindSnippet = { fg = "#F5EBD9", bg = "#D4A959" },
    -- CmpItemKindFolder = { fg = "#F5EBD9", bg = "#D4A959" },
    -- CmpItemKindMethod = { fg = "#DDE5F5", bg = "#6C8ED4" },
    -- CmpItemKindValue = { fg = "#DDE5F5", bg = "#6C8ED4" },
    -- CmpItemKindEnumMember = { fg = "#DDE5F5", bg = "#6C8ED4" },
    -- CmpItemKindInterface = { fg = "#D8EEEB", bg = "#58B5A8" },
    -- CmpItemKindColor = { fg = "#D8EEEB", bg = "#58B5A8" },
    -- CmpItemKindTypeParameter = { fg = "#D8EEEB", bg = "#58B5A8" },

    TelescopeNormal = { fg = cp.subtext0 },

    LeapLabelPrimary = { fg = nil, bg = cp.mauve, bold = true },

    LspSagaFinderSelection = { fg = cp.blue, bg = cp.base },
    FinderSpinnerBorder = { fg = cp.blue, bg = cp.base },
    LspSagaLspFinderBorder = { fg = cp.blue, bg = cp.base },
    FinderPreviewSearch = { bg = cp.base },
    LspSagaHoverBorder = { fg = cp.blue, bg = cp.base },
    LspFloatWinNormal = { bg = cp.base },
    LspFloatWinBorder = { fg = cp.blue, bg = cp.base },
    LspSagaBorderTitle = { fg = cp.blue, bg = cp.red },
    DefinitionBorder = { fg = cp.blue, bg = cp.base },
    DefinitionArrow = { fg = cp.red, bg = cp.base },
    DefinitionSearch = { fg = nil, bg = cp.surface0 },
    DefinitionFile = { bg = cp.base },
    LSOutlinePreviewBorder = { fg = cp.blue, bg = cp.base },
    LspSagaRenameBorder = { fg = cp.blue, bg = cp.base },

    MiniJump = { fg = nil, bg = cp.surface1, underline = true },

    LspSignatureActiveParameter = { fg = cp.pink, bold = true },

    WinBar = { fg = cp.text, bg = cp.base },
    WinBarInactive = { fg = cp.surface2, bg = cp.base },
    -- WinBarModActive = { fg = cp.red, bg = cp.base },
    -- WinBarModInactive = { fg = cp.red, bg = cp.base },
    WinBarFilenameActive = { fg = cp.base, bg = cp.pink, bold = true },
    WinBarFilenameInactive = { fg = cp.subtext0, bg = cp.base, bold = true },
    -- WinBarModified = { fg = cp.red },

    WhichKeyFloat = { bg = cp.surface0 },
    WhichKeyBorder = { fg = cp.blue, bg = cp.surface0 },
    -- ===============================================================================
    -- Language specific
    -- ===============================================================================
    tsxTSTagDelimiter = { fg = cp.maroon },
    ["@tag.delimiter.tsx"] = { fg = cp.maroon },
    jsxTSTagDelimiter = { fg = cp.maroon },
    javascriptTSTagDelimiter = { fg = cp.maroon },
  },
})
