require("plugins.packer-config")

require("plugins.treesitter.treesitter-config")

require("plugins.catppuccin-config")
require("plugins.indentline-config")
-- require("plugins.comment-config")
require("plugins.session-manager-config")
require("plugins.nvim-tree-config")
require("plugins.lualine-config")
-- require("plugins.bufferline-config")

-- require("plugins.bufdel-config")
require("plugins.mini-config")
require("plugins.undotree-config")
require("plugins.gitsigns-config")
require("plugins.dashboard-config")
-- require("plugins.lightspeed-config")
require("plugins.leap-config")
-- require("plugins.pounce-config")
-- require("plugins.hop-config")
require("plugins.colorizer-config")
require("plugins.which-key-config")
-- require("plugins.formatter-config")
-- require("plugins.notify-config")

require("plugins.null-ls-config")
require("plugins.lsp.lsp-config")
require("plugins.lsp.nvim-cmp-config")
require("plugins.lsp.nvim-navic-config")
require("plugins.lsp.lspsaga-config")
-- require("plugins.lsp.lsp_signature-config")

require("plugins.luasnip-config")
require("plugins.autopairs-config")
require("plugins.nvim-surround-config")

require("plugins.telescope.telescope-config")
require("plugins.telescope.telescope-file-browser")

require("plugins.nvim-web-devicons")
