require("plugins.packer-config")
require("plugins.autopairs-config")
require("plugins.catppuccin-config")
require("plugins.luasnip-config")
require("plugins.indentline-config")
require("plugins.comment-config")
require("plugins.nvim-tree-config")
require("plugins.lualine-config")
require("plugins.bufferline-config")
require("plugins.bufdel-config")
require("plugins.null-ls-config")
require("plugins.gitsigns-config")
require("plugins.dashboard-config")
require("plugins.auto-session-config")
require("plugins.lightspeed-config")
require("plugins.colorizer-config")
require("plugins.which-key-config")

require("plugins.lsp.lsp-config")
require("plugins.lsp.nvim-cmp-config")
require("plugins.nvim-gps-config")

require("plugins.treesitter.treesitter-config")

require("plugins.telescope.telescope-config")
