
#   # Kanagawa Alacritty Colors
# colors:
#   primary:
#     background: '0x1f1f28'
#     foreground: '0xdcd7ba'
#
#   normal:
#     black:   '0x090618'
#     red:     '0xc34043'
#     green:   '0x76946a'
#     yellow:  '0xc0a36e'
#     blue:    '0x7e9cd8'
#     magenta: '0x957fb8'
#     cyan:    '0x6a9589'
#     white:   '0xc8c093'
#
#   bright:
#     black:   '0x727169'
#     red:     '0xe82424'
#     green:   '0x98bb6c'
#     yellow:  '0xe6c384'
#     blue:    '0x7fb4ca'
#     magenta: '0x938aa9'
#     cyan:    '0x7aa89f'
#     white:   '0xdcd7ba'
#
#   selection:
#     background: '0x2d4f67'
#     foreground: '0xc8c093'
#
#   indexed_colors:
#     - { index: 16, color: '0xffa066' }
#     - { index: 17, color: '0xff5d62' }

[env]
  TERM = "xterm-256color"

[window]

  opacity = 0.98

  padding.x = 1
  padding.y = 3

  decorations = "buttonless"
  decorations_theme_variant = "Dark" # "Dark"

[font]

  normal.family = "JetbrainsMono Nerd Font"
  # normal.style = "Retina"

  bold.family = "JetbrainsMono Nerd Font"
  bold.style = "Retina"

  italic.family = "JetbrainsMono Nerd Font"

  bold_italic.family = "JetbrainsMono Nerd Font"
  bold_italic.style = "Retina Italic"

  size = 14.5

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.

[keyboard]
  bindings = [
  { key = ";", mods = "Control", chars = "þ" },
  { key= ".", mods= "Control", chars= "˛" },
  { key = ",", mods = "Control", chars = "˘" },

]

[general]
# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

live_config_reload = true

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  "~/.config/alacritty/kanagawa.toml"
]
