[colors.primary]
background = "#1F1F28"
foreground = "#D1D3D3"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1F1F28"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1F1F28"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1F1F28"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1F1F28"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1F1F28"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1F1F28"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1F1F28"
background = "#A6ADC8"

[colors.selection]
text = "#1F1F28"
background = "#F5E0DC"

[colors.normal]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#D1D3D3"

[colors.bright]
black = "#585B70"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#D1D3D3"

[colors.dim]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#D1D3D3"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

