theme = "catpuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
"Ñ" = "command_mode"

