# [[language]]
# name = "typescript"
# auto-format = false
# # pass format options according to https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration omitting the "[language].format." prefix.
# # config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

# [[language]]
# name = "tailwindcss"
# # scope = "source.css"
# # injection-regex = "(postcss|css|html)"
# # file-types = ["css"]
# roots = ["tailwind.config.js","tailwind.config.cjs"]
# language-servers = [ { command = "tailwindcss-language-server", args = ["-vvv", "--stdio"] } ]
# # config = { }
